### ISSUE TITLE
Переписать методы в UserPool без столь богатого использования вложенных if

### ISSUE THREAD

**Issue by Jimilian** [mid135/java_game_bomberman#4]
```
if (this.checkRegistration(cur.login) && this.checkLogIn(request)) {
                arraySessionId.remove(request.getSession().getId());
                return true;
            } else {
                return true;
            }
return false;
```

"Хорошо ли, плохо ли - всё одно" (с)

Предлагаю завести Enum, который будет иметь поля:
- OK
- AuthIncorrect

и так далее, чтобы каждое состояние имело свое понятное описание.

**Comment by mid135** [comment]
enum добавлен, замечание с вложеными if не до конца понятно .

**Comment by Jimilian** [comment]
код вида

```
if (...) {
  if (...) {
      if (...) {
             ...
      else (...) {
      ...
   else if (...) {
}
}
}
```

тяжело читается, поэтому можно либо вынести в отдельный метод какие-то проверки.
